// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFWuDANphFILeefj95X_aP4sWrPxQ6A5g',
    appId: '1:875968898129:web:0e241ebad2c973fd718470',
    messagingSenderId: '875968898129',
    projectId: 'solladal-game',
    authDomain: 'solladal-game.firebaseapp.com',
    databaseURL: 'https://solladal-game-default-rtdb.firebaseio.com',
    storageBucket: 'solladal-game.appspot.com',
    measurementId: 'G-WXQV0YTXKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGbxddi8wdxCRu00xSJn_wIV7GyaUQh2Y',
    appId: '1:875968898129:android:65cefe6e3c1892bf718470',
    messagingSenderId: '875968898129',
    projectId: 'solladal-game',
    databaseURL: 'https://solladal-game-default-rtdb.firebaseio.com',
    storageBucket: 'solladal-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUGVGHvi8wql-YxM9XR4CbVZV5bGgsJZw',
    appId: '1:875968898129:ios:a74c8356a3f089d7718470',
    messagingSenderId: '875968898129',
    projectId: 'solladal-game',
    databaseURL: 'https://solladal-game-default-rtdb.firebaseio.com',
    storageBucket: 'solladal-game.appspot.com',
    iosClientId: '875968898129-baqofpoouk99vi5bf7nn1uib9jn970io.apps.googleusercontent.com',
    iosBundleId: 'com.example.solladal',
  );
}
