// Mocks generated by Mockito 5.1.0 from annotations
// in tamil_wordle/test/UnitTest/game_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:tamil_wordle/src/key.dart' as _i4;
import 'package:tamil_wordle/src/keyboard.dart' as _i3;


/// A class which mocks [Keyboard].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyboard extends _i1.Mock implements _i3.Keyboard {
  MockKeyboard() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i4.Key> get keyboardMap =>
      (super.noSuchMethod(Invocation.getter(#keyboardMap),
          returnValue: <String, _i4.Key>{}) as Map<String, _i4.Key>);
  @override
  set keyboardMap(Map<String, _i4.Key>? _keyboardMap) =>
      super.noSuchMethod(Invocation.setter(#keyboardMap, _keyboardMap),
          returnValueForMissingStub: null);
  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);
  @override
  set isEnabled(bool? _isEnabled) =>
      super.noSuchMethod(Invocation.setter(#isEnabled, _isEnabled),
          returnValueForMissingStub: null);
}
