// Mocks generated by Mockito 5.1.0 from annotations
// in tamil_wordle/test/UnitTest/word_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:tamil_wordle/src/database.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i2.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get secretWord =>
      (super.noSuchMethod(Invocation.getter(#secretWord), returnValue: '')
          as String);
  @override
  List<List<String?>> get wordList =>
      (super.noSuchMethod(Invocation.getter(#wordList),
          returnValue: <List<String?>>[]) as List<List<String?>>);
  @override
  List<String> get keyList =>
      (super.noSuchMethod(Invocation.getter(#keyList), returnValue: <String>[])
          as List<String>);
}
